# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=180, unique=True)),
                ('token', models.CharField(default=None, max_length=180)),
                ('is_new', models.BinaryField(default=True)),
                ('user_id', models.IntegerField(default=-1, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
        ),
    ]
