# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 4, 10, 3, 0, 37, 777626), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
