# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160410_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_new',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
