# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
